### PR TITLE
TinyVec::fmt - fix pretty printing

### LINKED ISSUE #137: Pretty-print Debug format option
`tinyvec::TinyVec` has a different `Debug` pretty-print format to `std::vec::Vec` (and to the slice pretty-print format).

Example code:

```rust
use tinyvec::{tiny_vec, TinyVec};

fn main() {
    let xs: Vec<i32> = vec![1, 2, 3];
    println!("Vec: {:#?}", xs);

    let xs: TinyVec<[i32; 6]> = tiny_vec![1, 2, 3];
    println!("TinyVec: {:#?}", xs);
}
```
Output:
```
Vec: [
    1,
    2,
    3,
]
TinyVec: [1, 2, 3]
```
Expected output:
```
Vec: [
    1,
    2,
    3,
]
TinyVec: [
    1,
    2,
    3,
]
```
[Playground link.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e6020aaf95e673d253caf9381977309)

This is also the format used by the `dbg!` macro, which is where I originally noticed the difference.

### PR DESCRIPTION
**Pull request by Soveu**
Fixes #137

### CODE REVIEW

**Comment by Lokathor** [comment]
Can you do the same thing for ArrayVec too?

**Comment by Soveu** [comment]
I'll go through all the format `impl`s and see what else can be replaced with slice fmt

**Comment by Soveu** [comment]
I noticed that slices, arrays and std Vec do _not_ implement Display, Binary or any other formatting `impl`, only Debug.
Removing them (for consistency) here would be a breaking change, so I guess only Debug impls will be modified.

**Comment by Lokathor** [comment]
You would need to do the new line manually after each line is printed. I can merge this and do the rest myself later if you like.

**Comment by Soveu** [comment]
I mean, the changes to `Debug` are pretty simple, I was just busy with RL stuff for past few hours :D

**Comment by Lokathor** [comment]
Sure, no worries.

**Pull request merged**
