### PR TITLE
Implement linear time retain

### LINKED ISSUE #27: `ArrayVec::retain` is inefficient
The method loops like this:

```rust
  while i < self.len {
      if !acceptable(&self[i]) {
        self.remove(i);
      } else {
          i += 1;
      }
   }
```

Note that it calls `remove` within the loop. This itself modifies the length and moves all other items. Removing all items with this strategy is thus `O(n²)`. ~~Furthermore, the indexing gets corrupted as  soon as the first item is removed as `i += 1` is executed even when all further items were shifted backwards one element thus skipping over an element.~~ Missed that this was fixed in 66c99e290bcb352e84d0658ffee02b7270d2458d

### PR DESCRIPTION
**Pull request by HeroicKatora**
Fixes #27

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I forgot to use `take` here since this was rebased. Just wait a minute.

**Comment by HeroicKatora** [comment]
Ready for review.

**Comment by HeroicKatora** [comment]
No, this maintains
* cleared, good elements to the left
* then a number of defaulted elements that were removed
* followed by all remaining elements

On drop, the `rotate_left` moves all the middle defaulted elements to the end.

**Comment by Lokathor** [comment]
If the good elements are on the left why do we need to do the rotate? Just to try and have the arrayvec be in a more sane state for recovery after a panic?

**Comment by HeroicKatora** [comment]
To mimic the standard library implementation, the ArrayVec should contain all elements that have not yet been removed in case of panic. Since these are still on the far right we rotate them to the left.

**Pull request merged**
