### PR TITLE
use alternate printing when requested.

### PR DESCRIPTION
**Pull request by Lokathor**
Brings the https://github.com/Lokathor/tinyvec/pull/138 to all fmt styles on all three vec types we've got.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Why are we bothering with alternate printing when we have Display and Debug impls already? Doesn't Display serve the pretty-printing use cases?

**Comment by Lokathor** [comment]
They're already there because *not having them* is clearly wrong design (yes, i do specifically mean the standard library is wrong on this one).

and they're now pretty printing because someone asked toady.

**Comment by Lokathor** [comment]
specifically, this makes the printing be multi-line when the alternate flag is specified.

**Comment by Shnatsel** [comment]
Ah, this is about supporting the formatting arg. Got it.

**Pull request merged**
