### PR TITLE
Some Simplifications and efficiency changes

### PR DESCRIPTION
**Pull request by HeroicKatora**
These commits are best viewed one-by-one. Feel free to comment if specific ones should be dropped or done in a separate PR if they are controversial.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
The change of using `mem::take` is blocked on `1.36. Depends fully on which you prefer, it would also be possible to provide the straightforward implementation in the crate and switch at a later date.

**Comment by Lokathor** [comment]
Gotta keep 1.36 support.

Honestly I'd like to have 1.34 be the base line, so that it "just works" on stable debian, but without the `alloc` crate available it would be pointless to most people, and the people who'd still use it (the embedded folks) are on Nightly Rust anyway

**Comment by Lokathor** [comment]
That said, feel free to make a private version of `take` and use it in all these places.

**Comment by HeroicKatora** [comment]
All checks green now. Yay!

**Pull request merged**
