### PR TITLE
High priority doc grammar correction

### PR DESCRIPTION
**Pull request by bb010g**
[Cats Can Have Little a Salami.](https://knowyourmeme.com/photos/1642875)

---
This change is [Reviewable](https://reviewable.io/reviews/lokathor/tinyvec/20)

### CODE REVIEW

**Comment by Lokathor** [comment]
Unfortunately I consider the grammatical value above exactly matching the meme source

**Comment by Lokathor** [comment]
@bb010g i've seen the light and this will be in the next release.

**Comment by bb010g** [comment]
\o/

(I can't re-open the PR after deleting the branch, but `git am "$(curl -S 'https://github.com/Lokathor/tinyvec/commit/d6f9f6ee5796d9ce3c72d7e9739346429f9c5836.patch')"` should work to still merge it.)

**Comment by Lokathor** [comment]
it's part of the https://github.com/Lokathor/tinyvec/pull/72 pr

**Pull request closed without merging**
