### PR TITLE
Add into_inner method

### LINKED ISSUE #122: Add some kind of "into_inner" function to ArrayVec and TinyVec
In my program, I use `smallvec` to collect iterators into arrays. My strategy is:

```
let my_iterator = { /* ... */ };
let res: [Foobar; 24] = my_iterator.collect::<SmallVec<[Foobar; 24]>>().into_inner().unwrap();
```

In this scenario, `into_inner()` returns `Result<[Foobar; 24], SmallVec<[Foobar; 24]>>`, where `Ok(...)` is returned if and only if the length is equal to the array capacity.

I would like to use the `tinyvec` package in this program instead. Is it possible that something close to `into_inner()` could be implemented on the `ArrayVec` and `TinyVec` structures? I would be willing to implement this PR.

### PR DESCRIPTION
**Pull request by not-a-seagull**
This method adds the `into_inner` method to both `ArrayVec` and `TinyVec` and resolves #122. It also adds documentation and doc-tests for both of these functions.

Implementation questions:

- If the length of an `ArrayVec` is less than its capacity, should it return an error value or should it return the array with its default values? I have taken the latter option for the time being.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Why not return the inner `Vec` instead of erroring out in `TinyVec`?

**Comment by not-a-seagull** [comment]
I was mostly just copying `smallvec`'s way of doing it. However, it would certainly be possible to return an enum containing either an array or a vector. I'd like to hear Lokathor's thoughts on what the API should look like.

**Comment by Lokathor** [comment]
yeouch, lots of diff noise, guess we haven't formatted the repo in a little while.

For `TinyVec`, the inner fields are already public since it's just an enum, I don't think we need to have an `into_inner` method at all. People can already do a match and then handle the error however they want.

**Comment by Lokathor** [comment]
great! though also the example doesn't need to be a whole page :3 just a few lines showing that you can get the array out should be enough. I can fix that before publishing if you don't want to.

not sure why CI stopped, i'll restart it

**Pull request merged**
