### PR TITLE
Makes `tiny_vec!` go directly to the heap if the CAPACITY would have overflowed.

### PR DESCRIPTION
**Pull request by Lokathor**

### CODE REVIEW

**Comment by mgostIH** [comment]
For the counting hack we could also consider prior art, SmallVec seems to be using a counting helper: https://docs.rs/smallvec/1.1.0/src/smallvec/lib.rs.html#106

**Comment by Lokathor** [comment]
Well that's essentially what we have here, so that's a good sign.

**Comment by mgostIH** [comment]
Well yeah, the stringify! should be negligible but I don't know whether in debug mode it would bloat the executable (althought it's really minimal)

**Comment by Lokathor** [comment]
Actually... they're kinda doing it not as well. Because in this crate's version it's a `const`, the value is forced to be fully computed at compile time. So, debug / release would make no difference at runtime. There could be some small compile speed difference, but in this case I'm willing to pay that.

**Pull request merged**
