### PR TITLE
"try_*" functions and "to_vec" for arrayvec

### PR DESCRIPTION
**Pull request by Soveu**
Plus, a bit of rewrite of tinyvec to use them.

### CODE REVIEW

**Comment by Soveu** [comment]
I'm thinking if `to_vec` is a good name, because it consumes the items.
Maybe `into_vec` could be a better choice.

**Comment by Lokathor** [comment]
Well for one thing it looks like you added no tests at all >_>

**Comment by ThatsNoMoon** [comment]
@Soveu I have a `reserve` (and `reserve_exact`) test I made before I realized you were making this PR; you could take that from [my fork](https://github.com/ThatsNoMoon/tinyvec/blob/main/tests/tinyvec.rs#L70-L108).

**Comment by Soveu** [comment]
From [Vec::reserve_exact](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve_exact)
```
Note that the allocator may give the collection more space than it requests. 
Therefore, capacity can not be relied upon to be precisely minimal. 
Prefer reserve if future insertions are expected.
```
So technically tests for `reserve_exact` should be the same as for `exact`, `capacity() >= amount_requested`

**Comment by Soveu** [comment]
Appveyor died, because of `matches!` macro [*]

**Comment by Lokathor** [comment]
ah, yeah, gotta be really strict on keeping to a minimum version imy afraid.

**Comment by Soveu** [comment]
You can merge this PR (with  #80) if you don't have any objections.
I'm okay with the license, it doesn't change much for me anyway :wink:

**Comment by Lokathor** [comment]
okay, 80 first, then this, then we can update the 3rd PR to use reserve.

**Comment by Lokathor** [comment]
oh i forgot that i haven't reviewed this yet. I'll have to sit down and look closely later today.

In the mean time, it looks like merging #80 made some conflicts here.

**Comment by Soveu** [comment]
one conflict was because I left previously just one new line in `tests/tinyvec.rs` :D

**Comment by Soveu** [comment]
I am literally now sitting in github file editor, hoping that it will work :upside_down_face:

**Comment by Soveu** [comment]
Now I understand the merge conflict joke

**Comment by Soveu** [comment]
`An error occurred while generating the build script.` from Travis CI :(

**Comment by Lokathor** [comment]
there's already a `take` function in lib.rs actually

**Comment by Lokathor** [comment]
CI seems happy now. Travis is just flaky sometimes.

**Pull request merged**
