### PR TITLE
Replace Default bounds with Placeholder bounds

### PR DESCRIPTION
**Pull request by Lokathor**
Placeholder is automatically implemented for all Default, but you can also implement it for your own types without needing Default, if you really want.

* Closes https://github.com/Lokathor/tinyvec/issues/71

---

Should be ready to merge like this, if people decide we want this.

Though the generic bounds have changed, actually _not a single test_ had to be altered for the test suite to pass, so this is at least "inference compatible" with all previous usage.

Still, it's enough of a change that this would become a (breaking) 0.4 release if accepted.

### CODE REVIEW

**Comment by Lokathor** [comment]
Note that we _still_ can't impl Placeholder for NonZeroFoo, because of the blanket impl for Default types, it would make a conflict.

**Comment by Shnatsel** [comment]
Seeing that we still can't place NonZeroFoo in a TinyVec, I'm starting do doubt whether this change is worth the extra complexity it introduces. So right now I can neither approve nor reject this PR.

**Comment by Lokathor** [comment]
I think we'd need specialization or something for this to _maybe_ work in the future

**Comment by anderejd** [comment]
> Seeing that we still can't place NonZeroFoo in a TinyVec, I'm starting do doubt whether this change is worth the extra complexity it introduces. So right now I can neither approve nor reject this PR.

It seems like it already is possible if using a newtype wrapper, maybe that's not what you are trying to solve?

Thank you for this library btw!

```
use tinyvec::TinyVec;
use std::num::NonZeroU64;

struct MySpecialIndex(NonZeroU64);

impl Default for MySpecialIndex {
    fn default() -> Self {
        Self(NonZeroU64::new(1).unwrap())
    }
}

fn main() {
    let empty_tv = TinyVec::<[MySpecialIndex; 10]>::new();
    println!("Number of elements: {}", empty_tv.len())
}

```

**Comment by Lokathor** [comment]
Yeah, some people wanted to use this with NonZeroU8 without using a newtype.

I think i'm going to close this PR without a merge. The branch can sit in the repo and we could revive it later if necessary.

**Pull request closed without merging**
