### PR TITLE
Add a fill method, a panic-free extend alternative

### PR DESCRIPTION
**Pull request by HeroicKatora**
This is an alternative to `Extend::extend` method for cases where the
length of the iterator can not be checked. Since this vector can not
reallocate to increase its capacity, it is unclear what to do with
remaining elements in the iterator and the iterator itself. The
interface also provides no way to communicate this to the caller.

Closes: #31

### CODE REVIEW

**Comment by Shnatsel** [comment]
I'm not sure ArrayVec should expose `extend()` at all. It feels like too much of a footgun.

`fill()` makes more sense, but has its own tricky parts. For example, we cannot be sure that the iterator is fused, i.e. that it will not return `Some` again after returning `None`; this make it impossible to check whether the iterator has been used in its entirety without either encoding this information in the return value or requiring the iterator to be [Peekable](https://doc.rust-lang.org/std/iter/struct.Peekable.html).

**Comment by Shnatsel** [comment]
For comparison, arrayvec::ArrayVec's [`extend()`](https://docs.rs/arrayvec/0.5.1/arrayvec/struct.ArrayVec.html#method.extend) just ignores any extra elements from the iterator instead of panicking.

**Comment by HeroicKatora** [comment]
None of the tricky parts are internals though. If the user cares about the iterator being fused, they can call the method with `iter.fuse()`. Note that the variant that ignores extra elements is quite literally:

```rust
let _ = vec.fill(iter);
```

**Comment by Lokathor** [comment]
https://doc.rust-lang.org/src/alloc/vec.rs.html#2100

Vec already stops on the first None, so stopping "early" is already decided for us to some extent.

--

In general, anything that pushes into the vec is _more_ dangerous with an arrayvec. That's why people should be very careful. However, we can't actually always fix it perfectly. I think adding more to the type documentation would be appropriate though.

Normal users are expected to be using TinyVec, and ArrayVec being directly usable is a slightly "advanced" thing i guess you could say.

**Comment by Shnatsel** [comment]
My concern is that with the proposed interface it is impossible to distinguish between the following cases unless the iterator is fused:

1. ArrayVec was filled up to its capacity and the iterator returned None
1. ArrayVec was filled up to its capacity, and the iterator has some items remaining that did not fit

**Comment by HeroicKatora** [comment]
>   * ArrayVec was filled up to its capacity and the iterator returned None

This case never happens, the iterator is not polled after the vector has been filled. When the vector is not yet full then the iterator was polled exactly one more time than elements have been inserted, and it returned `None`.

**Comment by Shnatsel** [comment]
In that case I'm in favor of merging this, and also dropping `Extend` impl because that can be used in a generic context and the expectation for that trait seems to be that it will consume the entire iterator.

**Comment by Shnatsel** [comment]
Is `fill_from_iter` long enough?

**Comment by Lokathor** [comment]
something like that

**Pull request merged**
