### PR TITLE
Fuzz: drop workarounds for operations that may panic

### PR DESCRIPTION
**Pull request by Shnatsel**
Drop workarounds for operations that may panic now that rutenspitz compares panic behavior

cc @jakubadamw

### CODE REVIEW

**Comment by Shnatsel** [comment]
Oh , it's finding some mismatches in ArrayVec now! Interesting!

**Comment by jakubadamw** [comment]
LGTM. 👍

**Comment by Shnatsel** [comment]
ArrayVec panic is pointing to an integer overflow on this line:

https://github.com/Lokathor/tinyvec/blob/5758549693b979d9aff3105c062bc852062c0c26/src/arrayvec_drain.rs#L28

Operation triggering it: `v.drain(..=18446744073709551615);`

I am surprised that this panic is possible to detect in this setup at all. Does this mean that `Vec` doesn't panic here?

Side note: https://github.com/jakubadamw/rutenspitz/blob/master/DEBUGGING.md is complicated, lldb-specific (no gdb) and possibly requires rust-lldb as opposed to mainline. I've just added a `println!("Operations trace:\n{}", _op_trace);`

**Comment by Shnatsel** [comment]
Yep, `std::Vec` overflows silently: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0654621334a4a9da1917446f5c8571f0

**Comment by Shnatsel** [comment]
The same overflow was also discovered in TinyVec:

https://github.com/Lokathor/tinyvec/blob/5758549693b979d9aff3105c062bc852062c0c26/src/tinyvec.rs#L433

**Comment by Shnatsel** [comment]
CI is failing with DNS resolution errors.

**Comment by jakubadamw** [comment]
@Shnatsel, I used a regular lldb (`HFUZZ_DEBUGGER=lldb cargo hfuzz run-debug …`). In fact, I had issues with rust-lldb. 🙂 But yes, it is written with lldb in mind and perhaps could use some clarification.

**Comment by Nemo157** [comment]
That sounds worthy of an upstream bug report, silently failing to drain the vector :frowning:

**Comment by Nemo157** [comment]
Hmm, building with `-Z build-std` gives

```
thread 'main' panicked at 'attempt to add with overflow', /home/wim/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1322:29
```

so, the behaviour here is actually identical, except `std` is normally built in `release` mode and you are testing in `debug` mode.

**Comment by Shnatsel** [comment]
I've opened an issue against libstd: https://github.com/rust-lang/rust/issues/74909

**Comment by Shnatsel** [comment]
No further failures after 500 million executions of arrayish target and 125 million executions of tinyvec target

**Pull request merged**
