### PR TITLE
Implement `[value; N]` syntax support for `array_vec!`

### LINKED ISSUE #117: The `array_vec!` macro does not support the array-like `[T; N]` syntax you'd generally expect it to
Not a huge deal, but certainly something people might view as what is often called a "papercut" in the Rust community, as that syntax is supported by at least regular `vec!` and `smallvec!` as far as "Very Popular Data Structures™" go, and even in `staticvec` supporting it kind of just seemed like an immediate "must have" to me from day one.  
  
The entire implementation of the `staticvec!` macro is just this, if it helps at all:  
  
```rust
macro_rules! staticvec {
  ($($val:expr),* $(,)*) => {
    $crate::StaticVec::new_from_const_array([$($val),*])
  };
  ($val:expr; $n:expr) => {
    $crate::StaticVec::new_from_const_array([$val; $n])
  };
}
```

### PR DESCRIPTION
**Pull request by slightlyoutofphase**
Closes #117. I also improved one of the other variants of the macro a little bit while I was at it.

### CODE REVIEW

**Review by Lokathor — APPROVED** [review]
I like it, but I'm gonna ping Nemo as well for a double check.

**Comment by Nemo157** [comment]
Implementation looks fine, but it seems weird to support this syntax for `array_vec!` and not `tiny_vec!`.

**Comment by slightlyoutofphase** [comment]
> Implementation looks fine, but it seems weird to support this syntax for `array_vec!` and not `tiny_vec!`.

I can add that as well, if you'd like.

**Comment by slightlyoutofphase** [comment]
Ok, added it for `tiny_vec!` as well, and added a test.

**Comment by Nemo157** [comment]
```rust
// Given that this works:
let vec: TinyVec<[f32; 4]> = tiny_vec!(1.1, 1.1, 1.1);

// Should this work:
let vec: TinyVec<[f32; 4]> = tiny_vec![1.1; 3];
```

**Comment by slightlyoutofphase** [comment]
For both ArrayVec and TinyVec?

**Comment by Lokathor** [comment]
hmm, that's a very good question.

**Comment by Nemo157** [comment]
The first form works for both, so if it's possible (/easy enough) it seems good to have the second form for both.

**Comment by Lokathor** [comment]
@slightlyoutofphase Hi, looks like we all forgot about this a bit.

did you want to add that one final macro variant to this PR? Or I can just merge it now.

**Comment by Lokathor** [comment]
oh, forgot to say at the time. near as i can tell it looks like the requested style was already implemented by the time it was asked.

**Comment by Nemo157** [comment]
```
8 |     let vec: TinyVec<[f32; 4]> = tiny_vec![1.1; 3];
  |              -----------------   ^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 4 elements, found one with 3 elements
  |              |
  |              expected due to this
```

(I also just realised that the inverse could be supported by `tiny_vec!` (and not `array_vec!`): `let vec: TinyVec<[f32; 4]> = tiny_vec![1.1; 5];`, going directly to an allocation).

**Comment by slightlyoutofphase** [comment]
Hey guys, sorry I didn't get back to you. Basically, after playing around with a bunch of things, I found that it isn't quite possible to make the code example given by Nemo157, that is, this:

``` rust
// Given that this works:
let vec: TinyVec<[f32; 4]> = tiny_vec![1.1, 1.1, 1.1];

// Should this work:
let vec: TinyVec<[f32; 4]> = tiny_vec![1.1; 3];
```
work at the moment. The compiler isn't quite smart enough currently to see through the ambuguity such that both versions can exist and work in their appropriate contexts at the same time.

If it gets to the point where I think this can be done though, I'll for sure come back and add it for you if you want.

**Pull request merged**
